[general]
import = []
working_directory = "None"
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding = { x = 0, y = 0 }
position = { x = 0, y = 0 }

decorations = "Full"
opacity = 0.98
blur = false

title = "Terminator"
class = { general = "Alacritty", instance = "Alacritty" }
dynamic_title = true

[scrolling]
history = 5000 # Default is 10000
multiplier = 3

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Underline"

[colors.cursor]
cursor = "#f2cdcd"

[font]
size        = 13
normal      = { family = "SauceCodePro Nerd Font", style = "Medium" }
bold        = { family = "SauceCodePro Nerd Font", style = "Bold" }
italic      = { family = "SauceCodePro Nerd Font", style = "Italic" }
bold_italic = { family = "SauceCodePro Nerd Font", style = "Bold Italic" }

[mouse]
hide_when_typing = true

# Keybinds section
[keyboard]
bindings = [
    { mods = "Control|Shift", key = "C", action = "Copy" },
    { mods = "Control|Shift", key = "V", action = "Paste" },
]
